### PR TITLE
Updated several data set pages

### PR DESCRIPTION
**Pull request by pchristen**
and linked in files for cora-weight-vector

### CODE REVIEW

**Comment by ozgurakgun** [comment]
This looks much better :)

You can also make more commits and the preview will be updated.

Let me know when you want me to merge.

**Comment by pchristen** [comment]
I had to fix (hopefully) the link from Cora weight vectors to Cora - not sure if I got it correct.

**Comment by ozgurakgun** [comment]
That went into a separate PR again somehow...

**Comment by pchristen** [comment]
Bummer, sorry no idea why.

**Comment by ozgurakgun** [comment]
Do you want me to merge these?

**Comment by pchristen** [comment]
yes please.

**Pull request merged**
