### PR TITLE
Create local.md

### PR DESCRIPTION
**Pull request by pchristen**
A tag for data sets that are local (internal) to dlrep

### CODE REVIEW

**Comment by ozgurakgun** [comment]
This file is not under `_tags`.

**Comment by pchristen** [comment]
OK, remove the file and I create a new one under tags.

**Comment by ozgurakgun** [comment]
We could edit this pull request doing that. Or we can just close this one and you can create a new PR if you like?

**Comment by ozgurakgun** [comment]
Closing this one.

**Pull request closed without merging**
