### PR TITLE
Create public,md

### PR DESCRIPTION
**Pull request by pchristen**
Tag for publicly available data

### CODE REVIEW

**Review by pchristen — COMMENTED** [review]
fixed from , to . in name

**Comment by ozgurakgun** [comment]
@pchristen You seem to have created a bunch of PRs and closed most of them?

**Comment by ozgurakgun** [comment]
Also: it may be better to add multiple tags in one PR. That would require cloning the repository though, of course. (instead of using the GitHub web based editor...)

**Comment by pchristen** [comment]
@ozgurakgun Yes, I added tags I thought useful, will do more ow, likely also tasks.
I prefer not to to clone the repository but only use the Web editor.. hope that's OK

**Comment by ozgurakgun** [comment]
No problem at all for me.

**Comment by ozgurakgun** [comment]
But why did you close the pull requests? They cannot be merged now.

**Comment by pchristen** [comment]
Bugger - I thought once they are OKed I can close them..? :-(  Can I re-open them? Or how else to fix?

**Comment by pchristen** [comment]
yes, doing this now :-)

**Comment by pchristen** [comment]
Sorry, pressed wrong button :-(

**Pull request merged**
