### PR TITLE
Adding one of the entity resolution data sets from Leipzig

### PR DESCRIPTION
**Pull request by ozgurakgun**
more to come...

### CODE REVIEW

**Comment by ozgurakgun** [comment]
@pchristen -- I wasn't sure if they wanted us to host the CSV files ourselves, so I linked to their zip file.

It is a placeholder entry at the moment of course.

**Comment by pchristen** [comment]
@ozgurakgun Great, thanks heaps.. looks good. And a good idea to only link to the ZIP file.

**Comment by ozgurakgun** [comment]
This is only one of the data sets they have there by the way. The others should also be added. Merging this one.

**Comment by pchristen** [comment]
@ozgurakgun Thanks Ok.. maybe we can ask some of the others in the group to upload example (dummy) data sets.. we can remove those before going 'life' (i.e. before advertising dlrep).

**Pull request merged**
