### PR TITLE
Create GeCo.md

### PR DESCRIPTION
**Pull request by pchristen**
A new example of a data generator, not a data set

### CODE REVIEW

**Comment by ozgurakgun** [comment]
Each tag needs to be listed under the _tags directory. You can copy paste (and modify the contents) of another tag if you want @pchristen. The space shouldn't be a problem as long as the filename also contains the space. Let me know if I can help.

**Comment by ozgurakgun** [comment]
So for example for this one, using the web-editor may mean (I am not sure, I am not a user of it) that you cannot update the PR?

Can you actually create the "artificial data" tag to fix this PR?

**Comment by ozgurakgun** [comment]
Or if you intend to use "artificial" as the tag name, we can update this PR once that tag is added. I think #16 adds that.

**Comment by pchristen** [comment]
I updated the tags, lets see if it works.

**Comment by pchristen** [comment]
How do I add tasks to a data set?

**Pull request merged**
