### PR TITLE
Update Cora-weight-vectors.md

### PR DESCRIPTION
**Pull request by pchristen**
Fixed (?) link from Cora weight vectors to Cora - not sure

### CODE REVIEW

**Comment by pchristen** [comment]
Hm, the issue here is how to link a file in another folder..? I used ../ as with Linux, not sure.

**Comment by ozgurakgun** [comment]
Hmm.. Since we have a cora/Cora.md file, which in the website is changed to cora/Cora.html that is what we should use, I think.

Can you try ../cora/Cora.html?

I am not sure if you can, but it would be nice if you can update this PR with that change.

**Comment by pchristen** [comment]
I edited the file and clicked the 'update branch' button.. not sure what this does.

**Comment by ozgurakgun** [comment]
You don't seem to have edited the file from here, sorry.

**Comment by pchristen** [comment]
Weird, now I edited the version in my branch/fork.. sorry, I am confused again.

**Comment by pchristen** [comment]
Hm, ../Cora.html doesn't seem to work either :-(

**Comment by ozgurakgun** [comment]
> Can you try ../cora/Cora.html?

**Comment by pchristen** [comment]
Great, looks like it worked! Thanks Oz.

**Comment by pchristen** [comment]
Ready to be merged I think.

**Comment by ozgurakgun** [comment]
Grande!

**Comment by pchristen** [comment]
So I can close? Better check.. thanks.

**Comment by ozgurakgun** [comment]
Issues get opened/closed.
PRs get opened/closed/merged.

This one was a PR and it is merged now. Not sure if you can still close it. :)

**Comment by pchristen** [comment]
Thanks Oz for clarifying, yes I cannot close it as you have merged it. Thanks.

**Pull request merged**
