### PR TITLE
Replaced emails with homepages

### PR DESCRIPTION
**Pull request by pchristen**

### CODE REVIEW

**Comment by ozgurakgun** [comment]
Looks great @pchristen!

The bot did it's think it was so good though. :)

The bot thinks there is a problem, and that is one of the external links is broken.

The bot is wrong, I checked the link and it works. I may need to find a way to relax the external link validity checking or make it retry a few times. I can rerun travis manually, I'll do that now.

**Comment by pchristen** [comment]
@ozgurakgun  Thanks Oz, this might become an issue if we start to link in external sites where data sets are hosted.
I also just realised we need to fix Amy's surname to: O'Hara.

**Comment by ozgurakgun** [comment]
It doesn't seem very reliable. But I think external link checking is valuable.

I might just disable it for PRs. Because it can flag up unrelated problems, if a random external link goes down.

We can still run it every now and then I guess.

What do you think?

**Comment by pchristen** [comment]
@ozgurakgun  Sounds good to me! Thanks.

**Comment by ozgurakgun** [comment]
Now the bot built fine, the preview can be seen. I'll merge.

**Pull request merged**
