### PR TITLE
Acknowledgements

### PR DESCRIPTION
**Pull request by ozgurakgun**
- Acknowledging ADRC-S, INI.
- Alphabetising the maintainers.

### CODE REVIEW

**Comment by ozgurakgun** [comment]
@pchristen I just added ADRC-S and INI to the homepage, lmk if you like it. Link to preview build above in the bot-comment as always.

I feel like I am doing all of this alone without any feedback from anyone otherwise...

**Comment by pchristen** [comment]
@ozgurakgun Thanks heaps Oz, looks great, I will aim to add a link to our data generator sometimes today.
Yes, not much from the others so far. :-( Hopefully some feedback soon or by next week.

**Comment by ozgurakgun** [comment]
I am merging this, but would welcome more/better text about the acknowledgements.

Pinging @pchristen, @hckum, @grahamkirby, @cdibben.

**Comment by pchristen** [comment]
I added more to the acknowledgement. Should be enough I think, unless we want to add images with links.

**Pull request merged**
